name: Monitor Diário de Justiça TJCE

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *' # Roda todos os dias às 11:00 UTC (8h de Fortaleza)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TJCE Monitor Script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          DESTINATARIOS: ${{ secrets.DESTINATARIOS }}
          TJCE_CADERNOS: ${{ secrets.TJCE_CADERNOS }} # Nova secret
        run: python monitor_tjce.py # Nome do script atualizado
